# Generated by Django 3.0.8 on 2020-07-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=130)),
                ('content', models.TextField()),
            ],
        ),
    ]
